spring:
  application:
    name: yi-ai-agent

  datasource:
    url: jdbc:postgresql://rm-cn-em949h9q0000rt0o.rwlb.rds.aliyuncs.com/ai_agent

  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
#    指定mcp配置文件
    mcp:
      client:
#        request-timeout: 600000
        stdio:
          servers-configuration: classpath:mcp-servers-config.json
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8184

    dashscope:
      chat:
        options:
          model: qwen-plus

  profiles:
    active: local

server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yichen.yiaiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
